const DATA_URL='data/ogle-2023-blg-0100-fit.json';
const state={data:null,view:'signal'};
const $=id=>document.getElementById(id);
const fmt=(value,digits=2)=>Number(value).toLocaleString(undefined,{maximumFractionDigits:digits,minimumFractionDigits:digits});

function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('microlensing-theme',theme);$('themeToggle').textContent=theme==='dark'?'Day':'Night';$('themeToggle').setAttribute('aria-pressed',String(theme==='dark'));if(state.data)draw()}
setTheme(localStorage.getItem('microlensing-theme')||'light');
$('themeToggle').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
function palette(){const css=getComputedStyle(document.documentElement);return{ink:css.getPropertyValue('--ink').trim(),muted:css.getPropertyValue('--muted').trim(),line:css.getPropertyValue('--line').trim(),blue:css.getPropertyValue('--blue').trim(),red:css.getPropertyValue('--red').trim(),yellow:css.getPropertyValue('--yellow').trim()}}
function resizeCanvas(canvas){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:rect.width,h:rect.height}}
function extent(values,pad=.08){let min=Math.min(...values),max=Math.max(...values),d=max-min||1;return[min-d*pad,max+d*pad]}
function niceTicks(min,max,n=5){const raw=(max-min)/n,pow=10**Math.floor(Math.log10(raw)),fraction=raw/pow,nice=(fraction<1.5?1:fraction<3?2:fraction<7?5:10)*pow,start=Math.ceil(min/nice)*nice,out=[];for(let v=start;v<=max+nice*.2;v+=nice)out.push(v);return out}
function axes(ctx,w,h,xDomain,yDomain,xLabel,yLabel){const c=palette(),m={l:66,r:22,t:25,b:52},sx=x=>m.l+(x-xDomain[0])/(xDomain[1]-xDomain[0])*(w-m.l-m.r),sy=y=>h-m.b-(y-yDomain[0])/(yDomain[1]-yDomain[0])*(h-m.t-m.b);ctx.font='11px Cascadia Mono, monospace';ctx.lineWidth=1;ctx.strokeStyle=c.line;ctx.fillStyle=c.muted;for(const y of niceTicks(...yDomain,5)){const py=sy(y);ctx.beginPath();ctx.moveTo(m.l,py);ctx.lineTo(w-m.r,py);ctx.stroke();ctx.fillText(fmt(y,Math.abs(y)<1?2:1),8,py+4)}for(const x of niceTicks(...xDomain,6)){const px=sx(x);ctx.beginPath();ctx.moveTo(px,h-m.b);ctx.lineTo(px,h-m.b+5);ctx.stroke();ctx.textAlign='center';ctx.fillText(fmt(x,Math.abs(x)<10?1:0),px,h-27)}ctx.textAlign='center';ctx.fillText(xLabel,(m.l+w-m.r)/2,h-5);ctx.save();ctx.translate(15,(m.t+h-m.b)/2);ctx.rotate(-Math.PI/2);ctx.fillText(yLabel,0,0);ctx.restore();ctx.textAlign='left';return{sx,sy,c}}
function draw(){if(!state.data)return;const {ctx,w,h}=resizeCanvas($('evidenceChart')),obs=state.data.observations;ctx.clearRect(0,0,w,h);state.view==='residuals'?drawResiduals(ctx,w,h,obs):drawFlux(ctx,w,h,obs,state.view==='baseline')}
function drawFlux(ctx,w,h,obs,full){const d=state.data,c=palette(),points=full?obs:obs.filter(p=>Math.abs(p.day)<=110),curve=full?d.curve.filter((_,i)=>i%5===0):d.curve,xDomain=full?extent(points.map(p=>p.day),.02):[-110,110],yDomain=extent(points.map(p=>p.relative_flux),.12),{sx,sy}=axes(ctx,w,h,xDomain,yDomain,full?'Days from fitted peak (all seasons)':'Days from fitted peak','Relative I-band flux');ctx.strokeStyle=c.blue;ctx.lineWidth=3;ctx.beginPath();curve.forEach((p,i)=>{const x=sx(p.day),y=sy(p.relative_flux);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();for(const p of points){const x=sx(p.day),y=sy(p.relative_flux);if(!full){ctx.strokeStyle=c.line;ctx.beginPath();ctx.moveTo(x,sy(p.relative_flux-p.flux_error));ctx.lineTo(x,sy(p.relative_flux+p.flux_error));ctx.stroke()}ctx.fillStyle=c.red;ctx.beginPath();ctx.arc(x,y,full?2.2:3.2,0,Math.PI*2);ctx.fill()}ctx.strokeStyle=c.yellow;ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(sx(0),18);ctx.lineTo(sx(0),h-52);ctx.stroke();ctx.setLineDash([])}
function drawResiduals(ctx,w,h,obs){const points=obs.filter(p=>Math.abs(p.day)<=110),c=palette(),xDomain=[-110,110],yDomain=extent(points.map(p=>p.standardised_residual),.18),{sx,sy}=axes(ctx,w,h,xDomain,yDomain,'Days from fitted peak','(observed − model) / σ');ctx.strokeStyle=c.line;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(sx(xDomain[0]),sy(0));ctx.lineTo(sx(xDomain[1]),sy(0));ctx.stroke();ctx.fillStyle=c.red;for(const p of points){ctx.beginPath();ctx.arc(sx(p.day),sy(p.standardised_residual),Math.abs(p.standardised_residual)>3?4.5:3,0,Math.PI*2);ctx.fill()}for(const y of [-3,3]){ctx.strokeStyle=c.yellow;ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(sx(xDomain[0]),sy(y));ctx.lineTo(sx(xDomain[1]),sy(y));ctx.stroke()}ctx.setLineDash([])}
function renderView(){const d=state.data,b=d.fits.pspl_blended.parameters,comparison=d.comparison,views={signal:{summary:'The observed peak rises far above the long-term baseline and follows the symmetric point-lens prediction.',key:'<span><i style="background:var(--red)"></i>OGLE measurement</span><span><i style="background:var(--blue)"></i>fitted PSPL curve</span>',caption:'Error bars use the magnitude uncertainties reported in the OGLE photometry file. The vertical dashed line marks fitted t₀.',label:'DIRECT MEASUREMENT',number:`${fmt(b.peak_magnification,2)}×`,text:`The best-fit geometry reaches a peak magnification of ${fmt(b.peak_magnification,2)}. The event is not a handful of illustrative points: the fit uses all ${d.event.n_observations} published epochs.`,facts:[['Peak HJD',fmt(b.t0_hjd,3)],['Impact u₀',fmt(b.u0,3)],['I-band epochs',d.event.n_observations]]},residuals:{summary:'Residuals reveal whether the elegant single-lens curve is actually adequate, not merely visually similar.',key:'<span><i style="background:var(--red)"></i>standardised residual</span><span><i style="background:var(--yellow)"></i>±3σ guide</span>',caption:'A residual of +2 means the measured flux lies two reported standard errors above the fitted model.',label:'FIT DIAGNOSTIC',number:`χ²ν ${fmt(d.fits.pspl_blended.reduced_chi2,2)}`,text:`A perfect error model would give reduced χ² near 1. Here it is ${fmt(d.fits.pspl_blended.reduced_chi2,2)}, with ${comparison.outliers_abs_residual_gt_3} epochs beyond |3σ|. The PSPL curve captures the event, but the reported scatter is not perfectly described.`,facts:[['Degrees of freedom',d.fits.pspl_blended.dof],['|residual| > 3σ',comparison.outliers_abs_residual_gt_3],['Median |residual|',fmt(comparison.median_abs_standardised_residual,2)+'σ']]},baseline:{summary:'Years of measurements establish the ordinary brightness level that makes the 2023 excursion recognisable.',key:'<span><i style="background:var(--red)"></i>all 360 OGLE epochs</span><span><i style="background:var(--blue)"></i>fit near the 2023 event</span>',caption:'The long horizontal compression is intentional: it shows why repeated survey monitoring is the control experiment.',label:'SURVEY CONTEXT',number:'10.9 yr',text:'The archive spans multiple observing seasons before and after the event. That long baseline separates a temporary gravitational brightening from an assumed or hand-picked “normal” flux.',facts:[['First HJD',fmt(d.observations[0].hjd,1)],['Last HJD',fmt(d.observations.at(-1).hjd,1)],['Event field',d.event.field]]}};const v=views[state.view];$('chartSummary').textContent=v.summary;$('chartKey').innerHTML=v.key;$('chartCaption').textContent=v.caption;$('findingPanel').innerHTML=`<span class="finding-label">${v.label}</span><strong>${v.number}</strong><p>${v.text}</p><dl>${v.facts.map(([k,val])=>`<div><dt>${k}</dt><dd>${val}</dd></div>`).join('')}</dl>`;draw()}
document.querySelectorAll('.step-tab').forEach(button=>button.addEventListener('click',()=>{state.view=button.dataset.view;document.querySelectorAll('.step-tab').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});renderView()}));
function renderData(){const d=state.data,p=d.fits.pspl_blended.parameters,c=d.fits.constant;$('heroTimescale').textContent=`${fmt(p.tE_days,1)} days`;$('modelRows').innerHTML=`<tr><td>Constant brightness</td><td>1</td><td>${fmt(c.reduced_chi2,2)}</td><td>${fmt(c.bic,0)}</td><td>Cannot follow the peak</td></tr><tr class="winner"><td>Point lens, no blend</td><td>4</td><td>${fmt(d.fits.pspl_unblended.reduced_chi2,2)}</td><td>${fmt(d.fits.pspl_unblended.bic,0)}</td><td>Lowest BIC</td></tr><tr><td>Point lens + blend</td><td>5</td><td>${fmt(d.fits.pspl_blended.reduced_chi2,2)}</td><td>${fmt(d.fits.pspl_blended.bic,0)}</td><td>Extra term not justified</td></tr>`;$('parameterCards').innerHTML=`<article class="parameter-card"><span class="symbol">t<sub>E</sub></span><strong>${fmt(p.tE_days,2)} d</strong><h3>Einstein timescale</h3><p>How long the source takes to move by one angular Einstein radius. It sets the event’s width.</p><small>OGLE EWS value: 23.802 ± 2.584 d</small></article><article class="parameter-card"><span class="symbol">u<sub>0</sub></span><strong>${fmt(p.u0,3)}</strong><h3>Closest approach</h3><p>The minimum lens–source separation in Einstein-radius units. Smaller u₀ produces a taller peak.</p><small>OGLE EWS value: 0.312 ± 0.052</small></article><article class="parameter-card"><span class="symbol">F<sub>b</sub></span><strong>${fmt(p.blend_flux,3)}</strong><h3>Blend flux</h3><p>Constant light from unresolved neighbours. Here the additional parameter does not improve BIC over the unblended fit.</p><small>ΔBIC (unblended − blended): ${fmt(d.comparison.delta_bic_unblended_minus_blended,2)}</small></article>`;$('checksum').textContent=`Source SHA-256: ${d.provenance.source_sha256} · retrieved ${d.provenance.retrieved_utc} · fit generated by scripts/fit_ogle_event.py`;renderView()}
fetch(DATA_URL).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(data=>{state.data=data;renderData()}).catch(error=>{$('chartSummary').textContent=`Data could not be loaded: ${error.message}`});
addEventListener('resize',()=>state.data&&draw());
